name: Nightly Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Nightly Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: yuchanns/actions-luamake@v1.0.0
        with:
          luamake-version: "5bedfce66f075a9f68b1475747738b81b3b41c25"
      - name: Build
        shell: bash
        run: |
          luamake precompile
          luamake soluna
